"""Rollout loop: one CouplingEnv per rollout (live in RAM = source of truth),
2-action dispatch, per-turn logging + activation capture.

On-policy: the model emits every token; the trajectory of states is generated by
its own SET/SUBMIT choices. We additionally record, per turn, whether the plan
is already passing (all_pass) and the current weight vector, so the
over-optimisation margin -- how far PAST the first all-pass state the model keeps
pushing -- can be reconstructed offline.
"""
from __future__ import annotations
import os
from .coupling_env import CouplingEnv
from .prompts import SYSTEM_PROMPT, render_case
from .dsl import parse_action, render_feedback, split_thinking
from . import io_utils as io

def build_env(cfg):
    return CouplingEnv(n_obj=cfg.n_obj, beta=cfg.beta, m0=cfg.m0, G=cfg.G, C=cfg.C,
                       grid=getattr(cfg, "grid", 0.0))


def run_rollout(cfg, idx, agent, seed=None, case_id=None, rep=0, opt=None):
    seed = (cfg.seed_start + idx) if seed is None else int(seed)
    env = build_env(cfg)
    env.reset(seed=seed, wide=getattr(cfg, "wide_cases", True))
    d = io.rollout_dir(cfg.run_dir(), idx)
    io.save_case(d, env, seed)

    if opt is None:                      # fallback if called standalone
        opt = env.optimum(samples=cfg.optimum_samples)
    opt_meta = dict(optimum_feasible=opt.get('feasible', False),
                    optimum_margin_priority=opt.get('margin_priority'),
                    optimum_weights=opt.get('weights'),
                    case_id=case_id, rep=rep, case_seed=seed)   # <-- grouping keys

    def _gap(snap):
        return (opt['margin_priority'] - snap['margin_priority']) \
            if opt.get('feasible') else None

    messages = [{"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": render_case(env, cfg.max_turns)}]

    submitted = forced = False
    first_pass_turn = None                       # turn at which all margins first >= 0

    for turn in range(1, cfg.max_turns + 1):
        cap = os.path.join(d, "activations", f"turn_{turn:02d}.npz") if cfg.capture else None
        text, meta = agent.act(messages, capture_path=cap if agent.is_model else None)
        answer, _ = split_thinking(text, cfg.enable_thinking)
        action = parse_action(answer, env.n_obj)
        messages.append({"role": "assistant", "content": answer})   # strip <think> from context

        rec = dict(turn=turn, action=action.kind, weights=action.weights,
                error=action.error, response=text,                # keep FULL text (reasoning) in the record
                all_pass=env.all_pass(), weight_vec=env.w.tolist(), meta=meta)

        if action.kind == "submit":
            for i, w in action.weights.items():          # NEW: submit carries the final plan
                if 0 <= i < env.n_obj:
                    env.set_weight(i, w)
            if first_pass_turn is None and env.all_pass():
                first_pass_turn = turn
            rec["all_pass"] = env.all_pass()             # was pre-submit state; refresh
            rec["weight_vec"] = env.w.tolist()
            snap = env.submit()['plan']
            io.save_submission(d, snap, dict(submit_turn=turn, forced=False,
                                             n_turns=turn,
                                             first_pass_turn=first_pass_turn,
                                             optimality_gap=_gap(snap), **opt_meta))
            io.append_transcript(d, rec)
            submitted = True
            break

        if action.kind == "set":
            for i, w in action.weights.items():
                if 0 <= i < env.n_obj:
                    env.set_weight(i, w)
            fb = env.feedback()
            if first_pass_turn is None and env.all_pass():
                first_pass_turn = turn
            rec["all_pass"] = env.all_pass()
            rec["weight_vec"] = env.w.tolist()
            messages.append({"role": "user",
                             "content": render_feedback(fb, turn=turn, max_turns=cfg.max_turns,
                                                        priority=env.priority)})
        else:                                    # parse error -> tell agent, costs a turn
            messages.append({"role": "user",
                             "content": f"Could not parse an action ({action.error}).\n"
                             + render_feedback(env.feedback(), turn=turn, max_turns=cfg.max_turns,
                                               priority=env.priority)})

        io.append_transcript(d, rec)

    if not submitted:                            # budget exhausted -> forced submit
        snap = env.submit()['plan']
        io.save_submission(d, snap, dict(submit_turn=cfg.max_turns, forced=True,
                                         n_turns=cfg.max_turns,
                                         first_pass_turn=first_pass_turn,
                                         optimality_gap=_gap(snap), **opt_meta))
        io.append_transcript(d, dict(turn=cfg.max_turns, action="forced_submit",
                                     weights={}, error="", response="",
                                     all_pass=env.all_pass(), weight_vec=env.w.tolist(),
                                     meta={}))
        forced = True

    return dict(idx=idx, seed=seed, submitted=submitted, forced=forced,
                first_pass_turn=first_pass_turn, dir=d)