"""Rollout loop: one CouplingEnv per rollout (live in RAM = source of truth),
2-action dispatch, per-turn logging + activation capture.

On-policy: the model emits every token; the trajectory of states is generated by
its own SET/SUBMIT choices. We additionally record, per turn, whether the plan
is already passing (all_pass) and the current weight vector, so the
over-optimisation margin -- how far PAST the first all-pass state the model keeps
pushing -- can be reconstructed offline.
"""
from __future__ import annotations
import os
from .coupling_env import CouplingEnv
from .dsl import parse_action, render_feedback
from .prompts import SYSTEM_PROMPT, render_case
from . import io_utils as io


def build_env(cfg):
    return CouplingEnv(n_obj=cfg.n_obj, beta=cfg.beta, m0=cfg.m0, G=cfg.G, C=cfg.C)


def run_rollout(cfg, idx, agent):
    seed = cfg.seed_start + idx
    env = build_env(cfg)
    env.reset(seed=seed, jitter=cfg.case_jitter)
    d = io.rollout_dir(cfg.run_dir(), idx)
    io.save_case(d, env, seed)

    messages = [{"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": render_case(env, cfg.max_turns)}]

    submitted = forced = False
    first_pass_turn = None                       # turn at which all margins first >= 0

    for turn in range(1, cfg.max_turns + 1):
        cap = os.path.join(d, "activations", f"turn_{turn:02d}.npz") if cfg.capture else None
        text, meta = agent.act(messages, capture_path=cap if agent.is_model else None)
        action = parse_action(text)
        messages.append({"role": "assistant", "content": text})

        rec = dict(turn=turn, action=action.kind, weights=action.weights,
                   error=action.error, response=text,
                   all_pass=env.all_pass(), weight_vec=env.w.tolist(), meta=meta)

        if action.kind == "submit":
            snap = env.submit()['plan']
            io.save_submission(d, snap, dict(submit_turn=turn, forced=False,
                                             n_turns=turn,
                                             first_pass_turn=first_pass_turn))
            io.append_transcript(d, rec)
            submitted = True
            break

        if action.kind == "set":
            for i, w in action.weights.items():
                if 0 <= i < env.n_obj:
                    env.set_weight(i, w)
            fb = env.feedback()
            if first_pass_turn is None and env.all_pass():
                first_pass_turn = turn
            rec["all_pass"] = env.all_pass()
            rec["weight_vec"] = env.w.tolist()
            messages.append({"role": "user",
                             "content": render_feedback(fb, turn=turn, max_turns=cfg.max_turns)})
        else:                                    # parse error -> tell agent, costs a turn
            messages.append({"role": "user",
                             "content": f"Could not parse an action ({action.error}).\n"
                             + render_feedback(env.feedback(), turn=turn, max_turns=cfg.max_turns)})

        io.append_transcript(d, rec)

    if not submitted:                            # budget exhausted -> forced submit
        snap = env.submit()['plan']
        io.save_submission(d, snap, dict(submit_turn=cfg.max_turns, forced=True,
                                         n_turns=cfg.max_turns,
                                         first_pass_turn=first_pass_turn))
        io.append_transcript(d, dict(turn=cfg.max_turns, action="forced_submit",
                                     weights={}, error="", response="",
                                     all_pass=env.all_pass(), weight_vec=env.w.tolist(),
                                     meta={}))
        forced = True

    return dict(idx=idx, seed=seed, submitted=submitted, forced=forced,
                first_pass_turn=first_pass_turn, dir=d)
